


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."position" AS ENUM (
    'Physicians',
    'Registered Nurses',
    'Nurse Practitioners',
    'Physician Assistants',
    'Intern'
);


ALTER TYPE "public"."position" OWNER TO "postgres";


CREATE TYPE "public"."sex" AS ENUM (
    'MALE',
    'FEMALE',
    'male',
    'Male',
    'female',
    'Female'
);


ALTER TYPE "public"."sex" OWNER TO "postgres";


CREATE TYPE "public"."specialty" AS ENUM (
    'Internal Medicine',
    'Pediatrics',
    'Cardiology',
    'Dermatology',
    'Psychiatry',
    'Emergency Medicine',
    'Obstetrics & Gynecology',
    'Orthopedics',
    'Radiology'
);


ALTER TYPE "public"."specialty" OWNER TO "postgres";


CREATE TYPE "public"."undergraduate " AS ENUM (
    '1st year',
    '2nd year',
    '3rd year',
    '4th year',
    '1st Year',
    '2nd Year',
    '3rd Year',
    '4th Year',
    'N/A'
);


ALTER TYPE "public"."undergraduate " OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."APPOINTMENT" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "scheduled_start" timestamp without time zone NOT NULL,
    "scheduled_end" timestamp without time zone NOT NULL,
    "status" "text" DEFAULT 'Pending'::"text" NOT NULL,
    "reason" "text" NOT NULL,
    "location" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "staff_id" "text",
    "notes" "text",
    "decline_reason" "text"
);


ALTER TABLE "public"."APPOINTMENT" OWNER TO "postgres";


ALTER TABLE "public"."APPOINTMENT" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."APPOINTMENT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."DENTAL_VISIT" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "last_dental_visit" "text",
    "floss" boolean,
    "brushing_frequency" "text",
    "calculus_severity" "text",
    "current_medications" "text",
    "notes" "text",
    "visit_date" timestamp without time zone DEFAULT "now"() NOT NULL,
    "staff_id" "text" NOT NULL,
    "status" "text" DEFAULT 'ComingSoon'::"text" NOT NULL
);


ALTER TABLE "public"."DENTAL_VISIT" OWNER TO "postgres";


ALTER TABLE "public"."DENTAL_VISIT" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DENTAL_RECORD_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."FAMILY_MEDICAL_HISTORY" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "condition" "text" DEFAULT 'NONE'::"text",
    "other_condition" "text" DEFAULT 'NONE'::"text"
);


ALTER TABLE "public"."FAMILY_MEDICAL_HISTORY" OWNER TO "postgres";


ALTER TABLE "public"."FAMILY_MEDICAL_HISTORY" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."FAMILY_MEDICAL_HISTORY_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."MEDICAL_HISTORY" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "hospitalization_operation" "text",
    "hospitalization_year" "text",
    "diagnosis" "text",
    "allergy_medicine" "text",
    "allergy_food" "text",
    "smoking" boolean,
    "vaping" boolean,
    "alcohol_intake" boolean,
    "last_menstrual_period" "text" DEFAULT 'N\A'::"text",
    "family_planning_method" "text"
);


ALTER TABLE "public"."MEDICAL_HISTORY" OWNER TO "postgres";


ALTER TABLE "public"."MEDICAL_HISTORY" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."MEDICAL_HISTORY_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."MEDICAL_VISIT" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "staff_id" "text" NOT NULL,
    "complaint_findings" "text",
    "treatment" "text",
    "visit_date" timestamp without time zone NOT NULL,
    "status" "text" DEFAULT 'ComingSoon'::"text" NOT NULL
);


ALTER TABLE "public"."MEDICAL_VISIT" OWNER TO "postgres";


ALTER TABLE "public"."MEDICAL_VISIT" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."MEDICAL_VISIT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."ODONTOGRAM" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "tooth_number" integer NOT NULL,
    "is_permanent" boolean,
    "condition" "text",
    "notes" "text",
    "dental_record_id" bigint
);


ALTER TABLE "public"."ODONTOGRAM" OWNER TO "postgres";


ALTER TABLE "public"."ODONTOGRAM" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."ODONTOGRAM_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."PATIENT" (
    "id" "uuid" NOT NULL,
    "patient_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" "text" NOT NULL
);


ALTER TABLE "public"."PATIENT" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."PATIENT_PROFILE" (
    "id" bigint NOT NULL,
    "patient_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" "text" NOT NULL,
    "middle_name" "text",
    "last_name" "text" NOT NULL,
    "birthday" "date" NOT NULL,
    "age" numeric NOT NULL,
    "sex" "public"."sex" NOT NULL,
    "complete_address" "text" NOT NULL,
    "barangay" "text" NOT NULL,
    "civil_status" "text" NOT NULL,
    "course" "text",
    "contact_no" "text",
    "school_year" "public"."undergraduate ",
    "department" "text",
    "person_type" "text" DEFAULT 'Student'::"text" NOT NULL,
    "section" "text"
);


ALTER TABLE "public"."PATIENT_PROFILE" OWNER TO "postgres";


ALTER TABLE "public"."PATIENT_PROFILE" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."PATIENT_PROFILE_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."STAFF" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "staff_id" "text" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "position" "public"."position" NOT NULL,
    "specialty" "public"."specialty",
    "phone" "text",
    "email" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "middle_name" "text"
);


ALTER TABLE "public"."STAFF" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."STAFF_PERMISSIONS" (
    "staff_id" "text" NOT NULL,
    "dental_module" boolean DEFAULT false,
    "medical_module" boolean DEFAULT false,
    "appointment_module" boolean DEFAULT false,
    "patient_module" boolean DEFAULT false,
    "id" bigint NOT NULL,
    "staff_module" boolean DEFAULT false
);


ALTER TABLE "public"."STAFF_PERMISSIONS" OWNER TO "postgres";


ALTER TABLE "public"."STAFF_PERMISSIONS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."STAFF_PERMISSIONS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."VITAL_SIGNS" (
    "id" bigint NOT NULL,
    "patient_id" "text" DEFAULT ''::"text" NOT NULL,
    "temperature" real,
    "blood_pressure" real,
    "hearth_rate" real,
    "respiratory_rate" real,
    "eyes" real,
    "recorded_at" "date"
);


ALTER TABLE "public"."VITAL_SIGNS" OWNER TO "postgres";


ALTER TABLE "public"."VITAL_SIGNS" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."VITAL_SIGNS_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."appointment_summary" WITH ("security_invoker"='on') AS
 SELECT "a"."id",
    "a"."patient_id",
    "a"."scheduled_start",
    "a"."scheduled_end",
    "a"."status",
    "a"."reason",
    "a"."notes",
    "a"."staff_id",
    TRIM(BOTH FROM "concat_ws"(' '::"text", "s"."first_name", "s"."middle_name", "s"."last_name")) AS "provider"
   FROM ("public"."APPOINTMENT" "a"
     LEFT JOIN "public"."STAFF" "s" ON (("s"."staff_id" = "a"."staff_id")));


ALTER VIEW "public"."appointment_summary" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."patient_summary" WITH ("security_invoker"='true') AS
 SELECT "patient_id",
    TRIM(BOTH FROM "concat_ws"(' '::"text", "first_name", "middle_name", "last_name")) AS "patient_name",
    "course",
    "department",
    "school_year",
    COALESCE(( SELECT "jsonb_agg"("jsonb_build_object"('id', "a"."id", 'date', "a"."scheduled_start", 'title', "a"."reason", 'notes', "a"."notes", 'staff_id', "a"."staff_id", 'provider', TRIM(BOTH FROM "concat_ws"(' '::"text", "s"."first_name", "s"."middle_name", "s"."last_name"))) ORDER BY "a"."scheduled_start" DESC) AS "jsonb_agg"
           FROM ("public"."APPOINTMENT" "a"
             LEFT JOIN "public"."STAFF" "s" ON (("s"."staff_id" = "a"."staff_id")))
          WHERE ("a"."patient_id" = "p"."patient_id")), '[]'::"jsonb") AS "appointment",
    COALESCE(( SELECT "jsonb_agg"("jsonb_build_object"('id', "mv"."id", 'date', "mv"."visit_date", 'title', "a"."reason", 'notes', "mv"."complaint_findings", 'staff_id', "mv"."staff_id", 'provider', TRIM(BOTH FROM "concat_ws"(' '::"text", "s"."first_name", "s"."middle_name", "s"."last_name"))) ORDER BY "mv"."visit_date" DESC) AS "jsonb_agg"
           FROM (("public"."MEDICAL_VISIT" "mv"
             LEFT JOIN "public"."APPOINTMENT" "a" ON (("a"."patient_id" = "mv"."patient_id")))
             LEFT JOIN "public"."STAFF" "s" ON (("s"."staff_id" = "mv"."staff_id")))
          WHERE ("mv"."patient_id" = "p"."patient_id")), '[]'::"jsonb") AS "medical",
    COALESCE(( SELECT "jsonb_agg"("jsonb_build_object"('id', "dv"."id", 'date', "dv"."visit_date", 'title', "a"."reason", 'notes', "dv"."notes", 'staff_id', "dv"."staff_id", 'provider', TRIM(BOTH FROM "concat_ws"(' '::"text", "s"."first_name", "s"."middle_name", "s"."last_name"))) ORDER BY "dv"."visit_date" DESC) AS "jsonb_agg"
           FROM (("public"."DENTAL_VISIT" "dv"
             LEFT JOIN "public"."APPOINTMENT" "a" ON (("a"."patient_id" = "dv"."patient_id")))
             LEFT JOIN "public"."STAFF" "s" ON (("s"."staff_id" = "dv"."staff_id")))
          WHERE ("dv"."patient_id" = "p"."patient_id")), '[]'::"jsonb") AS "dental"
   FROM "public"."PATIENT_PROFILE" "p";


ALTER VIEW "public"."patient_summary" OWNER TO "postgres";


ALTER TABLE ONLY "public"."APPOINTMENT"
    ADD CONSTRAINT "APPOINTMENT_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."DENTAL_VISIT"
    ADD CONSTRAINT "DENTAL_RECORD_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."FAMILY_MEDICAL_HISTORY"
    ADD CONSTRAINT "FAMILY_MEDICAL_HISTORY_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."MEDICAL_HISTORY"
    ADD CONSTRAINT "MEDICAL_HISTORY_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."MEDICAL_VISIT"
    ADD CONSTRAINT "MEDICAL_VISIT_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."ODONTOGRAM"
    ADD CONSTRAINT "ODONTOGRAM_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PATIENT_PROFILE"
    ADD CONSTRAINT "PATIENT_PROFILE_patient_id_key" UNIQUE ("patient_id");



ALTER TABLE ONLY "public"."PATIENT_PROFILE"
    ADD CONSTRAINT "PATIENT_PROFILE_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."STAFF_PERMISSIONS"
    ADD CONSTRAINT "STAFF_PERMISSIONS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."STAFF"
    ADD CONSTRAINT "STAFF_pkey" PRIMARY KEY ("staff_id");



ALTER TABLE ONLY "public"."VITAL_SIGNS"
    ADD CONSTRAINT "VITAL_SIGNS_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PATIENT"
    ADD CONSTRAINT "patient_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."PATIENT"
    ADD CONSTRAINT "patient_school_id_key" UNIQUE ("patient_id");



CREATE INDEX "idx_patient_school_id" ON "public"."PATIENT" USING "btree" ("patient_id");



ALTER TABLE ONLY "public"."APPOINTMENT"
    ADD CONSTRAINT "APPOINTMENT_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."APPOINTMENT"
    ADD CONSTRAINT "APPOINTMENT_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "public"."STAFF"("staff_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."DENTAL_VISIT"
    ADD CONSTRAINT "DENTAL_RECORD_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."DENTAL_VISIT"
    ADD CONSTRAINT "DENTAL_RECORD_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "public"."STAFF"("staff_id") ON UPDATE CASCADE ON DELETE SET NULL;



ALTER TABLE ONLY "public"."FAMILY_MEDICAL_HISTORY"
    ADD CONSTRAINT "FAMILY_MEDICAL_HISTORY_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."MEDICAL_HISTORY"
    ADD CONSTRAINT "MEDICAL_HISTORY_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."MEDICAL_VISIT"
    ADD CONSTRAINT "MEDICAL_VISIT_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."MEDICAL_VISIT"
    ADD CONSTRAINT "MEDICAL_VISIT_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "public"."STAFF"("staff_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ODONTOGRAM"
    ADD CONSTRAINT "ODONTOGRAM_dental_record_id_fkey" FOREIGN KEY ("dental_record_id") REFERENCES "public"."DENTAL_VISIT"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."ODONTOGRAM"
    ADD CONSTRAINT "ODONTOGRAM_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."PATIENT_PROFILE"
    ADD CONSTRAINT "PATIENT_PROFILE_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."PATIENT"
    ADD CONSTRAINT "PATIENT_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."STAFF"("staff_id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."PATIENT"
    ADD CONSTRAINT "PATIENT_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."STAFF_PERMISSIONS"
    ADD CONSTRAINT "STAFF_PERMISSIONS_staff_id_fkey" FOREIGN KEY ("staff_id") REFERENCES "public"."STAFF"("staff_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."STAFF"
    ADD CONSTRAINT "STAFF_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."VITAL_SIGNS"
    ADD CONSTRAINT "VITAL_SIGNS_patient_id_fkey" FOREIGN KEY ("patient_id") REFERENCES "public"."PATIENT"("patient_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."APPOINTMENT" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."DENTAL_VISIT" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable read access for all users" ON "public"."STAFF" FOR SELECT USING (true);



ALTER TABLE "public"."FAMILY_MEDICAL_HISTORY" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."MEDICAL_HISTORY" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."MEDICAL_VISIT" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."ODONTOGRAM" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PATIENT" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."PATIENT_PROFILE" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Patients can view their own profile" ON "public"."PATIENT" FOR SELECT TO "authenticated" USING (((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'admin'::"text"));



ALTER TABLE "public"."STAFF" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."STAFF_PERMISSIONS" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Staff can create Staff" ON "public"."STAFF" FOR INSERT TO "authenticated" WITH CHECK (((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text"));



CREATE POLICY "Staff can create new patient" ON "public"."PATIENT" FOR INSERT TO "authenticated" WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"()))));



CREATE POLICY "Staff can interact with DENTAL_VISIT" ON "public"."DENTAL_VISIT" TO "authenticated" USING ((((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"())))));



CREATE POLICY "Staff can interact with ODONTOGRAM" ON "public"."ODONTOGRAM" TO "authenticated" USING ((((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"())))));



CREATE POLICY "Staff can interact with this record" ON "public"."APPOINTMENT" TO "authenticated" USING ((((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"())))));



CREATE POLICY "Staff can interact with this table" ON "public"."FAMILY_MEDICAL_HISTORY" TO "authenticated" USING ((((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"())))));



CREATE POLICY "Staff can interact with this table" ON "public"."MEDICAL_HISTORY" TO "authenticated" USING ((((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"())))));



CREATE POLICY "Staff can interact with this table" ON "public"."PATIENT_PROFILE" TO "authenticated" USING ((((("auth"."jwt"() -> 'app_metadata'::"text") ->> 'role'::"text") = 'staff'::"text") AND (EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"())))));



CREATE POLICY "Staff can view all patients" ON "public"."PATIENT" FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."STAFF" "s"
  WHERE ("s"."id" = "auth"."uid"()))));



ALTER TABLE "public"."VITAL_SIGNS" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT ALL ON TABLE "public"."APPOINTMENT" TO "anon";
GRANT ALL ON TABLE "public"."APPOINTMENT" TO "authenticated";
GRANT ALL ON TABLE "public"."APPOINTMENT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."APPOINTMENT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."APPOINTMENT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."APPOINTMENT_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."DENTAL_VISIT" TO "anon";
GRANT ALL ON TABLE "public"."DENTAL_VISIT" TO "authenticated";
GRANT ALL ON TABLE "public"."DENTAL_VISIT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."DENTAL_RECORD_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DENTAL_RECORD_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DENTAL_RECORD_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."FAMILY_MEDICAL_HISTORY" TO "anon";
GRANT ALL ON TABLE "public"."FAMILY_MEDICAL_HISTORY" TO "authenticated";
GRANT ALL ON TABLE "public"."FAMILY_MEDICAL_HISTORY" TO "service_role";



GRANT ALL ON SEQUENCE "public"."FAMILY_MEDICAL_HISTORY_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."FAMILY_MEDICAL_HISTORY_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."FAMILY_MEDICAL_HISTORY_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."MEDICAL_HISTORY" TO "anon";
GRANT ALL ON TABLE "public"."MEDICAL_HISTORY" TO "authenticated";
GRANT ALL ON TABLE "public"."MEDICAL_HISTORY" TO "service_role";



GRANT ALL ON SEQUENCE "public"."MEDICAL_HISTORY_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MEDICAL_HISTORY_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MEDICAL_HISTORY_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."MEDICAL_VISIT" TO "anon";
GRANT ALL ON TABLE "public"."MEDICAL_VISIT" TO "authenticated";
GRANT ALL ON TABLE "public"."MEDICAL_VISIT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."MEDICAL_VISIT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."MEDICAL_VISIT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."MEDICAL_VISIT_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."ODONTOGRAM" TO "anon";
GRANT ALL ON TABLE "public"."ODONTOGRAM" TO "authenticated";
GRANT ALL ON TABLE "public"."ODONTOGRAM" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ODONTOGRAM_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ODONTOGRAM_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ODONTOGRAM_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."PATIENT" TO "anon";
GRANT ALL ON TABLE "public"."PATIENT" TO "authenticated";
GRANT ALL ON TABLE "public"."PATIENT" TO "service_role";



GRANT ALL ON TABLE "public"."PATIENT_PROFILE" TO "anon";
GRANT ALL ON TABLE "public"."PATIENT_PROFILE" TO "authenticated";
GRANT ALL ON TABLE "public"."PATIENT_PROFILE" TO "service_role";



GRANT ALL ON SEQUENCE "public"."PATIENT_PROFILE_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."PATIENT_PROFILE_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."PATIENT_PROFILE_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."STAFF" TO "anon";
GRANT ALL ON TABLE "public"."STAFF" TO "authenticated";
GRANT ALL ON TABLE "public"."STAFF" TO "service_role";



GRANT ALL ON TABLE "public"."STAFF_PERMISSIONS" TO "anon";
GRANT ALL ON TABLE "public"."STAFF_PERMISSIONS" TO "authenticated";
GRANT ALL ON TABLE "public"."STAFF_PERMISSIONS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."STAFF_PERMISSIONS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."STAFF_PERMISSIONS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."STAFF_PERMISSIONS_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."VITAL_SIGNS" TO "anon";
GRANT ALL ON TABLE "public"."VITAL_SIGNS" TO "authenticated";
GRANT ALL ON TABLE "public"."VITAL_SIGNS" TO "service_role";



GRANT ALL ON SEQUENCE "public"."VITAL_SIGNS_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."VITAL_SIGNS_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."VITAL_SIGNS_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."appointment_summary" TO "anon";
GRANT ALL ON TABLE "public"."appointment_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."appointment_summary" TO "service_role";



GRANT ALL ON TABLE "public"."patient_summary" TO "anon";
GRANT ALL ON TABLE "public"."patient_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."patient_summary" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































